### ISSUE TITLE
PublisherTool doesn't calculate number of streams correctly.

### ISSUE THREAD

**Issue by brianhorst** [strangelydim/Aeron#2]
When a 5 different streamIds on one URI are specified, PublisherTool believes there is only one stream. The options.getStreams().size() returns the number of StreamDescriptors, which represents all of the stream IDs on an IP:PORT. So a channels option of "udp://localhost:31111#1-5" results in 1 StreamDescriptor.

It might be a good idea to track the total streams in PubSubOptions, or even change StreamDescriptor to represent just one channel + stream id combination.

**Comment by strangelydim** [comment]
Fixed in commit 60cbe5e2228e0b0dfc64963d65bc04fd039be483, so closing.
